language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      sudo: required
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cwd=$(pwd -W); fi
  - echo "CWD=$cwd"
  - export SCRIPTS=$cwd/travis
  - export BUILD_DIR=$cwd/build_skyline
  - export TEST_DIR=$cwd/test
  - export SV_TOP_DIR=$cwd
  - $SCRIPTS/travis_get_cmake_latest.sh
  - sudo apt-get -y install libboost-all-dev
  - pip install numpy

script:
  - $SCRIPTS/travis_build.sh
  - $SCRIPTS/travis_result_test.sh
