name: test
on: [push, pull_request]
jobs:
  build-ubuntu-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build solver
        shell: bash
        run: |
          sudo apt-get -y install libboost-all-dev
          mkdir build_skyline
          cd build_skyline
          cmake ..
          make
      - name: result tests
        shell: bash
        run: |
          pip install numpy
          cd test
          python run_tests.py
