name: test
on: [push, pull_request]
jobs:
  build-ubuntu-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: |
          mkdir build_skyline
          cd build_skyline
          cmake ..
          make
